services:
  server:
    build: .
    restart: on-failure
    stop_grace_period: 5s
    ports: 
      - "6754:3000"
    volumes: 
      - ${PWD}/data/config/.env:/app/.env
    environment:
      - CONFIG_PATH=/app/.env
